sudo: enabled
dist: trusty

language: python
python:
 - "3.6"

install:
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip install wheel codecov coverage

script:
 - $GOOGLE_KEYS > secret_key.json
 - py.test --cov-report xml --cov=gsheet

after_success:
 - codecov -t "$CODECOV_TOKEN"
